// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtj2xSyW02FAQWUrT2BT5ZmoYeF60uWVA',
    appId: '1:219323732008:web:7c069e2c8ac0d7bccea51d',
    messagingSenderId: '219323732008',
    projectId: 'subscriber-app-1de7a',
    authDomain: 'subscriber-app-1de7a.firebaseapp.com',
    storageBucket: 'subscriber-app-1de7a.appspot.com',
    measurementId: 'G-X5F20Z971Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4U4Gy-bCjbFDBMRLSGsAGTY5TR1iwYic',
    appId: '1:219323732008:android:0e557fb05a4d31edcea51d',
    messagingSenderId: '219323732008',
    projectId: 'subscriber-app-1de7a',
    storageBucket: 'subscriber-app-1de7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTpcOWuTQoGFFtve5wNHaWMW5vnnthKwQ',
    appId: '1:219323732008:ios:208772a99aaebffdcea51d',
    messagingSenderId: '219323732008',
    projectId: 'subscriber-app-1de7a',
    storageBucket: 'subscriber-app-1de7a.appspot.com',
    iosBundleId: 'com.skynet.skynet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTpcOWuTQoGFFtve5wNHaWMW5vnnthKwQ',
    appId: '1:219323732008:ios:3be1f78b4366fcb9cea51d',
    messagingSenderId: '219323732008',
    projectId: 'subscriber-app-1de7a',
    storageBucket: 'subscriber-app-1de7a.appspot.com',
    iosBundleId: 'com.skynet.skynet.RunnerTests',
  );
}
